### ISSUE TITLE
BidAskVol.lua:342: attempt to perform arithmetic on field '?'

### ISSUE THREAD

**Issue by andry81** [nick-nh/qlua#1]
Quik version: `7.27.2.1`

I have found on the internet an advanved version of the `BidAskVol.lua`, `BidAskVol2.lua`: https://yadi.sk/d/hKy8wcnkbYtfL

But there is bugs with `nil` in the `LastReadDeals[index]` around call to `ReadTrades` function and around `ds`.

I suggest these fixes:

# 1:
After this:
```
    if index == 1 then
      cache_VolBid={}
      cache_VolAsk={}
      LastReadDeals={} 
      Delta={}
      Delta[index]= 0
      LastReadDeals[index]= -1
    else
      LastReadDeals[index] = LastReadDeals[index-1]
      Delta[index] = Delta[index-1]
    end
```
Put that:
```
    if LastReadDeals[index] == nil then
      return nil, nil, nil, nil, nil
    end
```

# 2:
Check `ds` before the use:
```
function FindExistCandle(I, ds)
  local out = I
  while not CandleExist(out) and ds ~= nil and out <= ds:Size() do
    out = out +1
  end
  return out
end
```

PS:
Another issue with the `BidAskVol2.lua` is a noticable  slow down.

**Comment by nick-nh** [comment]
Это мой совсем старый индикатор.
Выложил более свежую версию.
Данного рода индикаторы будут медленными, т.к. происходит чтение таблицы обезличенных сделок в колбеке индикатора. Это приводит к замедлению работы всего терминала. Тем более, если таблица большая.
Более приавильно, выносить чтение ТОС в отдельный скрипт или dll, чтобы индикатор только выводил уже агрегированные данные.

**Comment by andry81** [comment]
> Выложил более свежую версию.

Похоже он не видится или не работает в Quick 7.27.2.1.
Пробовал менять имя на DeltaVolume, - не помогло.
Есть варианты это исправить?

**Comment by andry81** [comment]
Похоже в файле был какой-то странный символ пробела, который Quik не понимает. Помогла простая замена в Notepad++ на обычный пробел.

**Comment by nick-nh** [comment]
Гит-хаб портит кодировку на utf-8. Квик ее не понимает.
Надо все с гит-хаба забирать через буфер обмена.

**Comment by andry81** [comment]
Есть ещё проблема: каждый раз при свежем запуске Квика - график пустой, приходится его передобавлять чтобы он нарисовался. Можно это как-то пофиксить быстрее?

**Comment by nick-nh** [comment]
Дело в том, что Квик при запуске сначала инициализирует индикаторы, а уже потом загружает поток данных обезличеных сделок. В результате, не всегда получается, что индикатор получает данные при старте. Решение может быть таким - добавить ожидание потока данных сделок в индикатор. Но и это не всегда поможет, т.к. индикатор что-то выполняет при поступелении новых данных, а в случае неторгового времени, он просто не сможет выполнить даже это.

Передобавлять индикатор необязательно. Достаточно просто открыть свойства графики и нажать ОК.

**Comment by andry81** [comment]
> Достаточно просто открыть свойства графики и нажать ОК.

Не совсем понял что это значит, но попытка отредактировать инструмент и просто нажать на OK/Cancel ни к чему ни приводит. Как не приводит и обновления окна, или попытка добавить линию или инструмент. Реально помогает обновление таблицы по связи из другой таблицы или ручное передобавление областей..

**Comment by nick-nh** [comment]
Я специально проверил работу при закрытии Квика и открытии его заново. Вижу, что график заполнен. Просьба более подробно объяснить способ воспроизведения.
Также есть еще способ заставить перезапустить индикатор - это сменить интервал, а потом обратно. При смене интервала идет перестроение баров, а значит и перерисовка. Но при это в ТОС должны быть данные иначе нечего выводить.

**Comment by andry81** [comment]
> Просьба более подробно объяснить способ воспроизведения.

Так вроде нечего объяснять, просто запускаю и ничего не перерисовывается. Возможно из-за того, что много инструментов и оно может тупо висеть с минуту на запуске.

> Также есть еще способ заставить перезапустить индикатор - это сменить интервал, а потом обратно. При смене интервала идет перестроение баров, а значит и перерисовка.

Не, это тоже не помогает.

> Но при это в ТОС должны быть данные иначе нечего выводить.

Так может из-за того что долго загружаются обезличенные сделки? Так то данные есть и даже много.

**Comment by SVM-1977** [comment]
Здравствуйте. С начала августа индикатор BidAskVol.lua стал работать некорректно: при открытии Квика график пустой (так было всегда), но новые свечи рисуются корректно, Дельта считается с момента открытия. При попытке обновить пишет "слишком много ошибок", график естественно пустой, нет даже общего объёма. При комментировании строки 360 "return nil" общий объём отображает корректно, . В логе пишет: 
Wed Aug  4 18:23:01 2021 OnCalc() CandleExist(3133): true; T(3133) Wed Aug  4 18:05:00 2021; LastReadDeals -1
Wed Aug  4 18:23:01 2021 timeFrom Wed Aug  4 18:05:00 2021
Wed Aug  4 18:23:01 2021 timeTo Wed Aug  4 18:10:00 2021
а потом ниже
Wed Aug  4 18:23:43 2021 ------------------------------------------------------------
Wed Aug  4 18:23:43 2021 OnCalc() CandleExist(62046): true; T(62046) Wed Aug  4 18:23:00 2021; LastReadDeals nil
Wed Aug  4 18:23:43 2021 timeFrom Wed Aug  4 18:23:00 2021
Wed Aug  4 18:23:43 2021 timeTo Wed Aug  4 18:24:00 2021
В чём может быть проблема, подскажите?
