### ISSUE TITLE
qlua/scriptMonitor/scriptMonitor.lua

### ISSUE THREAD

**Issue by CyberRSR** [nick-nh/qlua#11]
Закрытие или остановка скрипта qlua/scriptMonitor/scriptMonitor.lua занимает очень много времени на quik 9.7.1. Квик при этом не отвечает.

**Comment by nick-nh** [comment]
В терминале действует правило - при остановке скрипта завершается поток в течении 5 секунд. В самом бесконечном цикле есть постоянная проверка переменной isRun и не будет выполнятся лишние действия. Но если в момент остановки происходит расчет одного из алгоритмов, т.е. выполнение цикла, то да, он может ожидать эти самые 5 секунд.
Впрочем, можно в каждом алгоритме внутри циклов тоже добавить проверку isRun.

**Comment by CyberRSR** [comment]
Да уже все перепробовал вроде.
Подвисает на время пропорционально продолжительности работы скрипта. Похоже очищает какие то данные из памяти, которые там непрерывно копятся. Подвисает, когда уже полностью отработал OnStop().
