### ISSUE TITLE
scriptMonitor.lua Error: time result cannot be represented in this installation 

### ISSUE THREAD

**Issue by CyberRSR** [nick-nh/qlua#12]
Появляется ошибка "time result cannot be represented in this installation" в строке:
if SEC_CODE_INDEX[i][cell] < DS:Size() or current_time > newTimeToCalculate and current_time < (os.time(timeCandle) + INTERVAL*60) then --new candle
Вроде эта проблема обсуждалась тут: https://forum.quik.ru/forum10/topic5509/

**Comment by nick-nh** [comment]
Да, после перехода на 5.3 в квике стали появляться такие ошибки, например, для пустых баров, не имеющих времени.
Надо добавлять проверку на корректность даты.

Например таким методом

local function is_date(val)
    if not type(val) == "table" then return false end
    local status = pcall(function() return os.time(val); end)
    return status
end

**Comment by nick-nh** [comment]
Добавил проверку.
