### ISSUE TITLE
Поправить настройки по умолчанию

### ISSUE THREAD

**Issue by kkaazzoo** [nick-nh/qlua#14]
Привет, спасибо за индикатор! [EIS.lua - Elder Impulse System.](https://github.com/nick-nh/qlua/blob/master/EIS.lua)

Единственный индикатор импульсной системы Элдера в открытом доступе для Quik!

Поставил, пользуюсь, чую что-то не то. Потом сравнил с оригинальным индикатором самого Элдера. Так и есть, работает неправильно. Пришлось поломать голову что не так. Оказалось что в настройках

macd_method         SMA

signal_method        SMA

значение SMA надо исправить на EMA

Это не ошибка, можно настроить в админке как нужно, но надо в коде поставить правильные значения по умолчанию. У меня прозрение на этот счет наступило через довольно длительный период.

**Comment by nick-nh** [comment]
Ок. Так просто измените в строке 26 на "EMA". И будет умолчание какое необходимо.
