### ISSUE TITLE
Не работает настройка в индикаторе TTM Squeeze

### ISSUE THREAD

**Issue by kkaazzoo** [nick-nh/qlua#16]
Привет, спасибо за индикатор! В индикаторе TTM Squeeze настройка Линия No Squezee не работает, точки не отображаются.
![2023-09-24_120215](https://github.com/nick-nh/qlua/assets/19167244/6f1fd0ce-eb25-4c48-bbd3-6155eaea0f5a)

**Comment by nick-nh** [comment]
Если речь про линию NO Squeeze, то точки появляются только если каналы Боллинджера и Кельтнера пересекаются.
Т.е. когда одна линия внутри другого канала, другая снаружи другого канала. Чаще всего канал Кельтнера полностью внутри канала ББ или полностью снаружи.

Впрочем, изменил условие на то, которое чаще всего используют на TradingView (). Видимо, сейчас все сравнивают работы с этим ресурсом, а не с MT5, исходя из алгоритма которого этот индикатор писался.

**Comment by kkaazzoo** [comment]
Обновил у себя, вообще точки перестали отображаться:-))

Например индикатор MT5  [Squeeze Momentum Indicator by Giles](https://www.mql5.com/ru/market/product/99367?utm_campaign=MetaTrader+5+Terminal&utm_medium=special&utm_source=Market+Product+details+in+community&source=MetaTrader+5+Desktop) всегда отображает точки 2 цветов, либо зона сжатия, либо импульс. Как я понял, его код полностью портирован с самого популярного варианта индикатора типа [Squeeze](https://ru.tradingview.com/script/nqQ1DT5a-Squeeze-Momentum-Indicator-LazyBear/) на  Tradingview.

На MT5 и Tradingview есть даже вариант индикатора с точками трех цветов, один цвет зона сжатия, второй цвет предупреждение об импульсе, третий цвет непосредственно импульс. 

Если я правильно понял вы изначально тоже исходили из трех цветов точек? Просто точку самого импульса решили не отображать?

Еще есть вопрос ко формуле расчета.

**Comment by nick-nh** [comment]
Действительно, локальная версия отличается от репозитария. Обновил. Видимо, занимался оптимизацией и не обновил файл.

Что касается исходника, то я уже не помню на базе какого был написан этот. Это был запрос написать такой же для Квика. Кажется в этой ветке был исходник https://forum.quik.ru/messages/forum10/message46454/topic4711/#message46454

Смысл у них един - показать момент когда канал ББ полностью внутри канала Кельтнера или снаружи. На TW выводят точки для неторговых ситуаций. Получается цветной зоопарк. Поэтому в прошлой версии выводился именно момент Squeeze, когда канал полностью внутри. А также выводилась точка когда канал частично внутри, что редко, но бывает.
