### ISSUE TITLE
Кракозябры в индикаторе регрессии

### ISSUE THREAD

**Issue by kkaazzoo** [nick-nh/qlua#17]
Привет, настройки индикатора регрессии частично с кракозябрами

![2024-05-17_124550](https://github.com/nick-nh/qlua/assets/19167244/6a073aec-eee2-41e4-8a03-6102f4276805)
![2024-05-17_124527](https://github.com/nick-nh/qlua/assets/19167244/12935d36-dc35-444e-ae44-ee726329aa86)

**Comment by nick-nh** [comment]
В описании к репозитарию написано, что необходимо обеспечить конвертацию файла в кодировку win1251 которую поддерживает терминал Квик. GitHub хранит файлы в кодировке UTF-8.
