### ISSUE TITLE
Библиотеки для QUIK 8.7

### ISSUE THREAD

**Issue by ramateur** [nick-nh/qlua#3]
Socket не работает с QUIK 8.7
error loading module 'socket.core' from file 'C:\FinamJunior\socket\core.dll':
	Не найден указанный модуль.
Можно собрать библиотеки для lua 5.3?

**Comment by nick-nh** [comment]
Добавил ссылку https://github.com/nick-nh/qlua/blob/master/lua_socket_ssl/socket_x64.zip
