### ISSUE TITLE
BidAskVol.lua trouble

### ISSUE THREAD

**Issue by SVM-1977** [nick-nh/qlua#4]
Здравствуйте. С начала августа индикатор BidAskVol.lua стал работать некорректно: при открытии Квика график дельты пустой (так, в принципе, было всегда), но новые свечи рисуются корректно, Дельта считается с момента открытия. При попытке обновить график пишет "слишком много ошибок", график естественно пустой, нет даже общего объёма (вернее он есть, но за границами видимой области, не вписан в масштаб). При комментировании строки 360 "return nil" общий объём отображает корректно, . В логе пишет:
Wed Aug 4 18:23:01 2021 OnCalc() CandleExist(3133): true; T(3133) Wed Aug 4 18:05:00 2021; LastReadDeals -1
Wed Aug 4 18:23:01 2021 timeFrom Wed Aug 4 18:05:00 2021
Wed Aug 4 18:23:01 2021 timeTo Wed Aug 4 18:10:00 2021
а потом ниже
Wed Aug 4 18:23:43 2021 ------------------------------------------------------------
Wed Aug 4 18:23:43 2021 OnCalc() CandleExist(62046): true; T(62046) Wed Aug 4 18:23:00 2021; LastReadDeals nil
Wed Aug 4 18:23:43 2021 timeFrom Wed Aug 4 18:23:00 2021
Wed Aug 4 18:23:43 2021 timeTo Wed Aug 4 18:24:00 2021
В чём может быть проблема, подскажите?

**Comment by SVM-1977** [comment]
О, спасибо огромное, новая версия работает отлично. Только не понял новый принцип построения кумулятивной дельты, поэтому изменил код для построения по-старому принципу.

**Comment by nick-nh** [comment]
В этой версии добавлен параметр showBarDelta, переключающий вывод с накопленной дельты за все время, на дельту отдельного бара.

**Comment by SVM-1977** [comment]
Отличный индикатор! Немного подредактировал под себя, поставил return 6 и дописал возможность одновременного вывода и накопленной дельты и дельты отдельного бара.  Спасибо за проделанную работу!
![2021-08-05 23_08_12- UID_ 153375](https://user-images.githubusercontent.com/88446731/128414510-54f170a3-9510-4da6-bde0-cf153588c4da.jpg)
