### ISSUE TITLE
Индикаторы для Quik

### ISSUE THREAD

**Issue by Mingary** [nick-nh/qlua#7]
Здравствуйте !
Подскажите, пожалуйста, занимаетесь ли Вы написанием индикаторов для Квика на основе индикаторов MT4 ? Если да, то на каких условиях ?
И возможна ли вообще такая процедура без потери функционала метастоковского индикатора ?

**Comment by nick-nh** [comment]
Добрый день.

Если код индикатора открыт, то можно переписать. Или если известна логика и ее можно формализовать. Правда необходимо учитывать ограничения по графическому представлению данных терминала Квик, в отличии от MT4-5

**Comment by nick-nh** [comment]
И, если есть предложения, то заводите ветку в Discussions. Все же Issues немного для другого.
